### ISSUE TITLE
클래스간, 이벤트 전달 방법에 대한 문의입니다.

### ISSUE THREAD

**Issue by giftof** [giftof/popupstory#1]
안녕하세요 멘토님.

클래스간 이벤트 전달 방법에 대한 문의입니다.

찾아본 방법들은..
- System.Action
- UnityAction
- EventHandler
- Observer(이건 정확한 사용법을 아직 찾아보지 못했습니다)
- Unirx (plugin)

같은 것들이 있었고, unirx 이외에는 기본적으로 delegate를 이용하는 방식으로 보였습니다.

질문은..
1. MVC패턴을 이용할때, 적합도가 높은 방법이 따로 있을까요?
2. Unirx는 stream방식으로 데이터를 전달하고 필요한 것만 구독하는(react같은? [제가 react를 잘 모릅니다만..]) 방식이라고 읽어보았습니다만, 멘토님이 접하신 업무에서는 애용되고 있을까요?
3. 2번을 질문한 의도는, 코드 스타일의 변경이 필요해보여서, 이쪽에 대한 연습이 추가로 필요할까? 라는 궁금 때문입니다.

현재는..
EventHandler를 이용해보고 있습니다.

감사합니다 :)

**Comment by jongfeel** [comment]
### About event

UnityAction이 나중에 Unity inspector에서 확인하고 처리하는 용도로 쓰기에 좋을 수 있습니다.
완전 code base로만 한다면 어떤 걸 써도 상관은 없을 거에요.

### MVC

MVC 구조로 한다고 하면 가장 쉬운 접근 방법이 View 처리를 하는 코드와 Controller 코드의 명확한 구분입니다.
검증하는 방법은 Controller 코드 만으로 unit test 코드 작성이 가능하면 됩니다.

### Unirx

스트림 방식으로 이벤트를 캡쳐 해서 처리한다는 게 기본 컨셉입니다.
음, 안하시는 걸 추천드립니다. 이거 하느라 중요한 시간이 다 갈 수도 있거든요.

**Comment by giftof** [comment]
감사합니다 ^^

**Comment by giftof** [comment]
멘토님 회사 프로젝트들은, 어떤 디자인패턴 이용하시는지 여쭤봅니다.
프로젝트마다 케바케일까요?
아니면, 유니티에 어울리는 '특정'패턴이 있을까요?

**Comment by jongfeel** [comment]
프로젝트마다 다릅니다가 정답에 가까운 대답입니다.

Unity는 보통 singleton 많이 쓰는데, 저는 그닥 좋아하지는 않습니다.
그 외에는 필요할때 마다 쓰긴 하는데

- builder
- observer
- simple command

요정도 쓰는거 같네요.

그런데 패턴을 배워서 적용하자는 사실 주니어 레벨 관점이고
내 프로젝트에서 왜 design pattern이 필요한지 설명이 되야 합니다.

그리고 진짜 중요한 건데 coding pattern, programming pattern이 아니라
왜 design pattern인지 다시 생각해야 합니다.
설계 라는 걸 제대로 해보지도 못한 채 코드 긁어와서 패턴이라고 흉내만 내 봤자 나중에 유지보수 할 떄 고통만 수반됩니다.
왜냐하면 내 프로젝트에 맞게 설계된 코드가 아니기 때문이죠.

결론

설계를 안해봤다면? design pattern은 무쓸모.

**Comment by giftof** [comment]
넵. 알겠습니다.

대략적이라도, 문서작업부터 하고
큰 덩어리 잡은뒤에, 관계도 그리고 그에 먖는거 잡아야 하려나봐요;;

지금 하는식으로는, 나중에 감당 안되는건 이미 겪어봤습니다만, 지금 만드는 것에 적당한 풀이 방식이 무엇인지 몰라서 우왕좌왕하는걸 보니.. 그런것 같으네요 ^^;;

감사합니다 ^^
